version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - linkedin-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single broker setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - linkedin-network

  kafbat-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafbat-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - linkedin-network

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      - POSTGRES_DB=notificationDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - linkedin-network
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  posts-db:
    image: postgres:16
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - linkedin-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  connections-db:
    image: neo4j
    container_name: connections-db
    environment:
      - NEO4J_AUTH=neo4j/password  # Set your username and password
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    volumes:
      - connections-db-data:/data  # Persist data
    networks:
      - linkedin-network

  discovery-server:
    image: nouman886/linkedin-app-discovery-server
    container_name: discovery-server
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  posts-service:
    image: nouman886/linkedin-app-posts-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - posts-db
      - kafka

  user-service:
    image: nouman886/linkedin-app-user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - user-db
      - kafka

  notification-service:
    image: nouman886/linkedin-app-notification-service
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - notification-db
      - kafka

  connections-service:
    image: nouman886/linkedin-app-connections-service
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - connections-db
      - kafka

  api-gateway:
    image: nouman886/linkedin-app/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - linkedin-network
    depends_on:
      - discovery-server

networks:
  linkedin-network:

volumes:
  kafka_data:
  notification-db-data:
  posts-db-data:
  user-db-data:
  connections-db-data:
