# disable eureka properties
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

USER_SERVICE_URL: http://user-service
POSTS_SERVICE_URL: http://posts-service
CONNECTIONS_SERVICE_URL: http://connections-service
NOTIFICATION_SERVICE_URL: http://notification-service

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
