spring:
  application:
    name: user-service

# DB Configuration
  datasource:
    url: jdbc:postgresql://user-db:5432/userDB
    username: user
    password: password
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Server port
server:
  port: 9020

  servlet:
    context-path: /users

# Jwt Secret Key
jwt:
  secretKey: kljfhqa4uiowy93w84y90238q467v598ybvjalfi3uyo7qi24q347q98377
