spring:
  application:
    name: connections-service

# neo4j (graphDB) configuration
  neo4j:
#    uri: ${NEO4J_DB_URL}
    uri: bolt://connections-db:7687
    authentication:
      username: neo4j
      password: password
#      username: ${NEO4J_DB_USERNAME}
#      password: ${NEO4J_DB_PASSWORD}

# Kafka Configuration
  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 9030
  servlet:
    context-path: /connections

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
