spring:
  application:
    name: posts-service

# DB configuration
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:posts-db}:5432/${DB_NAME:postsDB}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

# Kafka Configuration
  kafka:
    bootstrap-servers: kafka:9092
#    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Server port configuration
server:
  port: 9010

  servlet:
    context-path: /posts
